### PR TITLE
Invalid Input err. message

### PR DESCRIPTION
**Pull request by GEp1c**
Fixing 'Invalid Input' message while creating new pages (sections, intersections,...)

### CODE REVIEW

**Comment by ShiraNai7** [comment]
I just tried creating all page types locally in development mode and haven't received any errors. Care to elaborate?

(Also - default values for most non-essential DB table columns have been already implemented in the upcoming major version relesase.)

**Comment by GEp1c** [comment]
Same as here: http://sunlight.shira.cz/index.php?m=topic&id=19774 (which is for 7.5.3).

I just cloned 7.5.4 and runned install, after installation opened administration and tried to create some page types (only galleries worked). Then I discovered that while creating sections only var1 and var2 are set in $custom_array and then got error with missing default values of columns. There were no default values for var1 to var4 after 7.5.4 installation.

**Comment by ShiraNai7** [comment]
This might have something to do with MySQL's sql_mode STRICT_ALL_TABLES being enabled. It is disabled by default so this is very rarely an issue.

Adding default column values is definitely the right way to fix this, but I don't want to touch the DB structure of the 7.x releases anymore (to preserve database backup compatibility).

This will be resolved when 8.0.0 is released.

In the meantime, you could try creating a custom plugin to disable this where needed:

_plugins/extend/mysql_config/mysql_config.php_

```php
<?php
    
_extend('reg', 'sys.init', function () {
    DB::query("SET SESSION sql_mode = ''");
});
```

I can't test the above code at the moment, but it should work.

**Comment by ShiraNai7** [comment]
In case anyone finds this: The `SET sql_mode=''` "fix" has been implemented in 7.5.5.

**Pull request closed without merging**
